Repository Team-Tokkit/Tokkit-Client, pull requests merged in 2025-06, with the labels that each got.

#131 Refactor: 가맹점주 Skeleton UI 적용
  app/landing-page/components/PullHandle.tsx
  app/merchant/dashboard/components/MerchantRecentTransaction.tsx
  app/merchant/dashboard/components/SalesStatistics.tsx
  app/merchant/dashboard/components/VoucherSearch.tsx
  app/merchant/dashboard/components/WalletCardSkeleton.tsx
  app/merchant/dashboard/page.tsx
  app/merchant/mypage/change-simple-password/components/StepIntro.tsx
  app/merchant/mypage/change-simple-password/components/StepVerifyCurrent.tsx
  app/merchant/mypage/change-simple-password/page.tsx
  app/merchant/mypage/components/MenuList.tsx
  app/merchant/mypage/components/ProfileCard.tsx
  app/merchant/mypage/page.tsx
  app/merchant/wallet/components/WalletSkeleton.tsx
  app/merchant/wallet/convert/components/AmountStep.tsx
  app/merchant/wallet/convert/components/CompleteStep.tsx
  app/merchant/wallet/convert/components/ConfirmStep.tsx
  app/merchant/wallet/convert/components/ConvertSkeleton.tsx
  app/merchant/wallet/convert/components/ProcessingStep.tsx
  app/merchant/wallet/convert/components/VerifySimplePassword.tsx
  app/merchant/wallet/convert/page.tsx
  app/merchant/wallet/page.tsx
  app/payment/components/VerifySimplePassword.tsx
  app/wallet/components/common/TransactionList.tsx
  app/wallet/components/common/WalletSkeleton.tsx
  app/wallet/components/convert/BalanceCard.tsx
  app/wallet/page.tsx
  components/common/AmountInput.tsx
  components/common/LoadingOverlay.tsx
Labels: REFACTOR

#136 Refactor: 이미지 경로 설정을 환경에 따라 동적으로 처리
  app/my-vouchers/components/MyVoucherCard.tsx
  app/my-vouchers/components/MyVoucherHeader.tsx
  app/my-vouchers/details/[voucherOwnershipId]/page.tsx
  app/vouchers/components/HeaderImage.tsx
  app/vouchers/components/VoucherCard.tsx
  app/vouchers/components/VoucherPurchaseCard.tsx
  app/vouchers/purchase/page.tsx
  lib/api/getImageSrc.ts
  next.config.ts
Labels: REFACTOR

#141 fix: build 에러 해결
  app/merchant/wallet/components/WalletClient.tsx
  app/merchant/wallet/page.tsx
Labels: FIX

#142 [DEPLOY] v1.0.6
  app/merchant/wallet/components/WalletClient.tsx
  app/merchant/wallet/page.tsx
Labels: RELEASE

#144 fix: 사업자 등록증 ocr 이후 페이지 롤백
  app/merchant/signup/business/components/AddressSearchModal.tsx
  app/merchant/signup/business/components/BusinessHeader.tsx
  app/merchant/signup/business/components/InfoStep.tsx
  app/merchant/signup/business/page.tsx
Labels: FIX

#147 Fix: imageurl 오류 수정
  app/payment/components/VerifySimplePassword.tsx
  app/vouchers/purchase/verify/page.tsx
  components/common/LoadingOverlay.tsx
  lib/api/getImageSrc.ts
Labels: FIX
