Repository Team-Tokkit/Tokkit-Client, pull requests merged in 2025-05, with the labels that each got.

#19 ✨ Feat: Kakao Map 구현 완료
  README.md
  app/offline-stores/api/store-service.ts
  app/offline-stores/components/StoreCategoryFilter.tsx
  app/offline-stores/components/StoreCategoryToggleButton.tsx
  app/offline-stores/components/StoreItem.tsx
  app/offline-stores/components/StoreList.tsx
  app/offline-stores/components/StoreListToggleButton.tsx
  app/offline-stores/components/StoreLocateButton.tsx
  app/offline-stores/components/StoreSearchButton.tsx
  app/offline-stores/components/StoreSearchInput.tsx
  app/offline-stores/page.tsx
  app/offline-stores/types/index.ts
  app/offline-stores/types/kakao.d.ts
  app/offline-stores/utils/map-overlay.ts
  app/offline-stores/utils/map-utils.ts
  lib/getApiUrl.ts
  package-lock.json
  package.json
  public/images/current-location-marker.png
  public/images/tokkit-marker.png
Labels: FEAT

#18 Refactor: 공지사항 최종 프론트 수정
  app/notice/[id]/page.tsx
  app/notice/components/NoticeItem.tsx
  app/notice/components/NoticeList.tsx
  app/notice/components/SkeletonDetail.tsx
  app/notice/components/SkeletonList.tsx
  app/notice/page.tsx
  components/common/Header.tsx
  components/common/Pagination.tsx
  components/notice/NoticeItem.tsx
  components/notice/NoticeList.tsx
  components/ui/button.tsx
  data/notice.ts
  lib/getApiUrl.ts
  lib/utils.ts
  package-lock.json
Labels: REFACTOR

#22 Feat: 랜딩 페이지 및 CBDC 알아보기 페이지 구현
  app/landing-page/components/CBDCTab.tsx
  app/landing-page/components/CardDetailMap.tsx
  app/landing-page/components/LandingMain.tsx
  app/landing-page/components/PullHandle.tsx
  app/landing-page/components/TokenInfoCard.tsx
  app/landing-page/components/token-detail/CBDCIntroCard.tsx
  app/landing-page/components/token-detail/FastTransferCard.tsx
  app/landing-page/components/token-detail/FinanceAccessCard.tsx
  app/landing-page/components/token-detail/QRCodeCard.tsx
  app/landing-page/data/CardInfoData.ts
  app/page.tsx
  components/pull-handle.tsx
  components/token-info-card.tsx
  public/images/barcode.svg
  public/images/fast-transfer.png
  public/images/fianace-access.png
  public/images/qrcode.png
Labels: FEAT

#26 Feat: 유저 대시보드 컴포넌트 분리
  app/dashboard/componenets/DashboardHeader.tsx
  app/dashboard/componenets/NoticeSection.tsx
  app/dashboard/componenets/PaymentButton.tsx
  app/dashboard/componenets/QuickMenu.tsx
  app/dashboard/componenets/RecentTransactions.tsx
  app/dashboard/componenets/WalletCard.tsx
  app/dashboard/page.tsx
  app/signup/wallet/contact/page.tsx
Labels: FEAT

#27 Feat: 알림 페이지 컴포넌트 분리
  app/notifications/components/NotificationEmptyState.tsx
  app/notifications/components/NotificationHeader.tsx
  app/notifications/components/NotificationIcon.tsx
  app/notifications/components/NotificationItem.tsx
  app/notifications/components/NotificationList.tsx
  app/notifications/components/NotificationSkeleton.tsx
  app/notifications/components/NotificationTabs.tsx
  app/notifications/page.tsx
  app/notifications/settings/components/NotificationPolicyInfo.tsx
  app/notifications/settings/components/NotificationSettingHeader.tsx
  app/notifications/settings/components/NotificationSettingItem.tsx
  app/notifications/settings/components/NotificationSettingSkeleton.tsx
  app/notifications/settings/page.tsx
  components/ui/switch.tsx
Labels: FEAT

#28 Feat: 유저 마이페이지 컴포넌트 분리
  app/mypage/components/LogoutDialog.tsx
  app/mypage/components/MenuList.tsx
  app/mypage/components/MypageHeader.tsx
  app/mypage/edit/components/SuccessNotice.tsx
  app/mypage/edit/components/card/EmailChangeDialog.tsx
  app/mypage/edit/components/card/ProfileCard.tsx
  app/mypage/edit/components/card/ProfileCardHeader.tsx
  app/mypage/edit/components/card/ProfileForm.tsx
  app/mypage/edit/components/header/ProfileHeader.tsx
  app/mypage/edit/page.tsx
  app/mypage/page.tsx
  components/ui/dialog.tsx
Labels: FEAT

#29 Feat: 유저 대시보드 페이지 api 연동
  app/dashboard/api/wallet-info.ts
  app/dashboard/componenets/WalletCard.tsx
  app/dashboard/page.tsx
  components/common/WithAuth.tsx
  lib/cookies.ts
  middleware.ts
Labels: FEAT

#24 Feat/#7 바우처 관련 페이지 구현
  app/my-vouchers/components/MyStoreList.tsx
  app/my-vouchers/components/MyStoreModal.tsx
  app/my-vouchers/components/MyVoucherCard.tsx
  app/my-vouchers/components/MyVoucherHeader.tsx
  app/my-vouchers/components/MyVoucherInfo.tsx
  app/my-vouchers/components/MyVoucherList.tsx
  app/my-vouchers/components/MyVoucherSearchBar.tsx
  app/my-vouchers/components/MyVoucherTabFilter.tsx
  app/my-vouchers/components/StatusBadge.tsx
  app/my-vouchers/details/[voucherOwnershipId]/page.tsx
  app/my-vouchers/page.tsx
  app/my-vouchers/types/my-voucher.ts
  app/vouchers/components/ExpandableSection.tsx
  app/vouchers/components/HeaderImage.tsx
  app/vouchers/components/Pagination.tsx
  app/vouchers/components/RecommendedVouchersSection.tsx
  app/vouchers/components/StoreList.tsx
  app/vouchers/components/StoreModal.tsx
  app/vouchers/components/VoucherCard.tsx
  app/vouchers/components/VoucherCategoryWithFilter.tsx
  app/vouchers/components/VoucherHeader.tsx
  app/vouchers/components/VoucherInfo.tsx
  app/vouchers/components/VoucherList.tsx
  app/vouchers/components/VoucherSearchBar.tsx
  app/vouchers/details/[id]/page.tsx
  app/vouchers/page.tsx
  app/vouchers/types/voucher.ts
  components/ui/tabs.tsx
  lib/api/voucher.ts
  types/store.ts
Labels: FEAT

#31 Feat/#30 내 바우처 삭제 페이지 구현
  app/my-vouchers/components/MyVoucherCard.tsx
  app/my-vouchers/components/MyVoucherList.tsx
  app/my-vouchers/page.tsx
  lib/api/voucher.ts
Labels: FEAT

#33 Feat: 마이페이지 구현
  app/dashboard/api/wallet-info.ts
  app/dashboard/page.tsx
  app/login/components/LoginForm.tsx
  app/mypage/api/user-info.ts
  app/mypage/api/user-logout.ts
  app/mypage/change-pin/api/verify-simple-password.ts
  app/mypage/change-pin/components/ChangePinHeader.tsx
  app/mypage/change-pin/components/ChangePinLayout.tsx
  app/mypage/change-pin/components/StepComplete.tsx
  app/mypage/change-pin/components/StepConfirmPin.tsx
  app/mypage/change-pin/components/StepIntro.tsx
  app/mypage/change-pin/components/StepNewPin.tsx
  app/mypage/change-pin/components/StepVerifyCurrent.tsx
  app/mypage/change-pin/page.tsx
  app/mypage/components/LogoutDialog.tsx
  app/mypage/components/MypageHeader.tsx
  app/mypage/edit/api/email.ts
  app/mypage/edit/api/update-user-info.ts
  app/mypage/edit/components/card/EmailChangeDialog.tsx
  app/mypage/edit/components/card/ProfileForm.tsx
  app/mypage/edit/page.tsx
  app/mypage/page.tsx
  app/mypage/reset-pin/api/reset-simple-password.ts
  app/mypage/reset-pin/components/ResetPinComplete.tsx
  app/mypage/reset-pin/components/ResetPinForm.tsx
  app/mypage/reset-pin/components/ResetPinHeader.tsx
  app/mypage/reset-pin/page.tsx
  app/reset-password/api/reset-password-auth.ts
  app/reset-password/components/ResetPasswordFrom.tsx
  app/reset-password/components/ResetPasswordResult.tsx
  app/reset-password/page.tsx
  components/common/WithAuth.tsx
  components/virtual-keypad.tsx
  lib/cookies.ts
  lib/fetchWithAuth.ts
  public/images/bunny-complete.png
  public/images/bunny-lock.png
Labels: FEAT

#15 Feat: 전자지갑 상세 페이지 구현
  app/notice/page.tsx
  app/wallet/components/AmountStep.tsx
  app/wallet/components/CompleteStep.tsx
  app/wallet/components/ConfirmStep.tsx
  app/wallet/components/ProcessingStep.tsx
  app/wallet/components/common/ConvertButton.tsx
  app/wallet/components/common/InfoBox.tsx
  app/wallet/components/common/TransactionCardContent.tsx
  app/wallet/components/common/TransactionList.tsx
  app/wallet/components/common/WalletCard.tsx
  app/wallet/components/common/WalletGuide.tsx
  app/wallet/components/convert/BalanceCard.tsx
  app/wallet/components/convert/ConvertPreview.tsx
  app/wallet/components/guide/GuideIntroCard.tsx
  app/wallet/components/guide/GuideList.tsx
  app/wallet/components/totalhistory/Calendar.tsx
  app/wallet/components/totalhistory/Category.tsx
  app/wallet/components/totalhistory/SearchBar.tsx
  app/wallet/convert/[type]/page.tsx
  app/wallet/guide/page.tsx
  app/wallet/page.tsx
  app/wallet/totaltransaction/[id]/page.tsx
  app/wallet/totaltransaction/page.tsx
  components/common/AmountInput.tsx
  components/common/SimplePassWord.tsx
  data/dashboard/notices.ts
  data/wallet/guideContents.ts
  public/images/arrow-down.gif
  public/images/deposit-to-token.gif
  public/images/error-bunny-transparent.png
  public/images/loading-bunny.png
  public/images/store-bunny.png
  public/images/token-to-deposit.gif
Labels: FEAT

#34 refactor: virtual keypad 컴포넌트 분리 적용
  app/signup/wallet/password/components/SimplePasswordStep.tsx
Labels: FEAT

#37 refactor: 예금, 토큰 전환 api 연동 및 컴포넌트 폴더 이름 수정
  app/dashboard/api/wallet-info.ts
  app/dashboard/componenets/DashboardHeader.tsx
  app/dashboard/componenets/NoticeSection.tsx
  app/dashboard/componenets/PaymentButton.tsx
  app/dashboard/componenets/QuickMenu.tsx
  app/dashboard/componenets/RecentTransactions.tsx
  app/dashboard/componenets/WalletCard.tsx
  app/dashboard/components/WalletCard.tsx
  app/dashboard/page.tsx
  app/vouchers/components/VoucherList.tsx
  app/wallet/convert/[type]/page.tsx
  components/common/SimplePassWord.tsx
Labels: REFACTOR

#38 refactor: api 경로 수정
  app/wallet/page.tsx
Labels: REFACTOR

#39 feat: 결제 api 연동
  app/dashboard/api/wallet-info.ts
  app/dashboard/page.tsx
  app/login/api/use-login.ts
  app/notice/page.tsx
  app/payment/api/payment.ts
  app/payment/components/AmountBox.tsx
  app/payment/components/MerchantInfoCard.tsx
  app/payment/components/PaymentCarousel.tsx
  app/payment/components/VerifySimplePassword.tsx
  app/payment/page.tsx
  app/signup/wallet/password/components/SimplePasswordStep.tsx
  app/wallet/api/wallet.ts
  app/wallet/convert/[type]/page.tsx
  app/wallet/page.tsx
  data/payment/storeqr.ts
  lib/parseJwt.ts
Labels: FEAT

#40 fix: 토큰에서 예금 전환 이슈 해결
  app/wallet/components/ProcessingStep.tsx
  app/wallet/convert/[type]/page.tsx
Labels: FEAT

#44 Feat: 가맹점주 랜딩페이지 구현
  app/landing-page/components/LandingMain.tsx
  app/merchant/components/MascotImage.tsx
  app/merchant/page.tsx
  components/page-header.tsx
  public/images/merchant-bunny.png
  public/images/store-bunny.png
Labels: FEAT

#49 Feat: 가맹점주 인증/인가 구현
  app/merchant/login/api/merchant-login.ts
  app/merchant/login/components/MerchantLoginForm.tsx
  app/merchant/login/components/MerchantLoginHeader.tsx
  app/merchant/login/components/MerchantLogo.tsx
  app/merchant/login/components/SwitchToUserButton.tsx
  app/merchant/login/page.tsx
  app/merchant/signup/business/api/business-ocr.ts
  app/merchant/signup/business/api/region.ts
  app/merchant/signup/business/components/AddressSearchModal.tsx
  app/merchant/signup/business/components/BusinessHeader.tsx
  app/merchant/signup/business/components/CaptureStep.tsx
  app/merchant/signup/business/components/InfoStep.tsx
  app/merchant/signup/business/page.tsx
  app/merchant/signup/components/MerchantTermsHeader.tsx
  app/merchant/signup/components/TermsAgreementCard.tsx
  app/merchant/signup/components/TermsAlert.tsx
  app/merchant/signup/components/TermsModal.tsx
  app/merchant/signup/data/merchant-terms.ts
  app/merchant/signup/page.tsx
  app/merchant/signup/wallet/complete/components/AccountNumberCard.tsx
  app/merchant/signup/wallet/complete/components/CompleteFooterButton.tsx
  app/merchant/signup/wallet/complete/components/UsageGuideList.tsx
  app/merchant/signup/wallet/complete/components/WalletCompleteContent.tsx
  app/merchant/signup/wallet/complete/page.tsx
  app/merchant/signup/wallet/components/wallet-intro.tsx
  app/merchant/signup/wallet/contact/api/register-auth.ts
  app/merchant/signup/wallet/contact/components/EmailVerificationBlock.tsx
  app/merchant/signup/wallet/contact/components/FormFeedbackMessage.tsx
  app/merchant/signup/wallet/contact/components/PasswordInputBlock.tsx
  app/merchant/signup/wallet/contact/components/PhoneInputBlock.tsx
  app/merchant/signup/wallet/contact/components/SubmitButton.tsx
  app/merchant/signup/wallet/contact/page.tsx
  app/merchant/signup/wallet/page.tsx
  app/merchant/signup/wallet/password/components/SimplePasswordStep.tsx
  app/merchant/signup/wallet/password/page.tsx
  app/merchant/signup/wallet/terms/[id]/page.tsx
  app/merchant/signup/wallet/terms/components/TermModal.tsx
  app/merchant/signup/wallet/terms/components/TermsAgreementPage.tsx
  app/merchant/signup/wallet/terms/components/TermsCardList.tsx
  app/merchant/signup/wallet/terms/data/walletTerms.ts
  app/merchant/signup/wallet/terms/page.tsx
  app/merchant/signup/wallet/verify/api/ocr.ts
  app/merchant/signup/wallet/verify/components/CaptureStep.tsx
  app/merchant/signup/wallet/verify/components/ReviewStep.tsx
  app/merchant/signup/wallet/verify/page.tsx
Labels: FEAT

#47 Refactor: 내 바우처 코드 리팩토링
  app/my-vouchers/components/MyStoreModal.tsx
  app/my-vouchers/details/[voucherOwnershipId]/page.tsx
  app/my-vouchers/page.tsx
  app/vouchers/purchase/verify/page.tsx
  components/common/LoadingOverlay.tsx
  next.config.ts
Labels: REFACTOR

#50 fix: 전환하기 페이지 오류 해결
  app/wallet/convert/[type]/page.tsx
Labels: FIX

#52 Feat: 가맹점주 대시보드 페이지 구현
  app/merchant/dashboard/components/MerchantHeader.tsx
  app/merchant/dashboard/components/NoticeSlider.tsx
  app/merchant/dashboard/components/SalesStatistics.tsx
  app/merchant/dashboard/components/VoucherSearch.tsx
  app/merchant/dashboard/components/WalletCard.tsx
  app/merchant/dashboard/page.tsx
  app/merchant/vouchers/[id]/page.tsx
  app/merchant/vouchers/page.tsx
  app/payment/qr-test/page.tsx
  data/payment/storeqr.ts
  public/search-icon.png
  public/simple-bar-chart.png
  public/simple-monthly-calendar.png
Labels: FEAT

#53 Chore/#48 유저 페이지 통합 테스트
  app/layout.tsx
  app/my-vouchers/components/MyVoucherCard.tsx
  app/my-vouchers/components/MyVoucherInfo.tsx
  app/my-vouchers/types/my-voucher.ts
  app/notifications/components/NotificationTabs.tsx
  app/offline-stores/api/store-service.ts
  public/images/favicon.ico
  public/placeholder-logo.png
  public/placeholder-logo.svg
  public/placeholder-user.jpg
  public/placeholder.jpg
  public/placeholder.svg
Labels: CHORE

#54 ✨ feat: QR 인식 api 연동
  app/dashboard/api/wallet-info.ts
  app/payment/api/payment.ts
  app/payment/components/AmountBox.tsx
  app/payment/components/ManualBox.tsx
  app/payment/components/MerchantInfoCard.tsx
  app/payment/components/PaymentCarousel.tsx
  app/payment/components/ResultBox.tsx
  app/payment/components/VerifySimplePassword.tsx
  app/payment/page.tsx
  app/payment/qr-test/page.tsx
  app/wallet/totaltransaction/page.tsx
  data/payment/storeqr.ts
Labels: FEAT

#60 Feat: 가맹점주 대시보드 구현
  app/merchant/dashboard/api/daily-income.ts
  app/merchant/dashboard/api/merchant-recent-transactions.ts
  app/merchant/dashboard/api/merchant-wallet-info.ts
  app/merchant/dashboard/components/MerchantHeader.tsx
  app/merchant/dashboard/components/MerchantRecentTransaction.tsx
  app/merchant/dashboard/components/NoticeSection.tsx
  app/merchant/dashboard/components/NoticeSlider.tsx
  app/merchant/dashboard/components/SalesStatistics.tsx
  app/merchant/dashboard/components/TransactionList.tsx
  app/merchant/dashboard/components/VoucherSearch.tsx
  app/merchant/dashboard/components/WalletCard.tsx
  app/merchant/dashboard/page.tsx
  app/merchant/login/api/merchant-login.ts
  app/merchant/wallet/components/ConvertButton.tsx
  app/merchant/wallet/components/WalletCard.tsx
  app/merchant/wallet/components/WalletGuide.tsx
  app/merchant/wallet/guide/components/GuideIntroCard.tsx
  app/merchant/wallet/guide/components/GuideList.tsx
  app/merchant/wallet/guide/components/InfoBox.tsx
  app/merchant/wallet/guide/page.tsx
  app/merchant/wallet/page.tsx
  app/merchant/wallet/totaltransaction/[id]/page.tsx
  app/merchant/wallet/totaltransaction/components/Calendar.tsx
  app/merchant/wallet/totaltransaction/components/Category.tsx
  app/merchant/wallet/totaltransaction/components/SearchBar.tsx
  app/merchant/wallet/totaltransaction/page.tsx
  app/notice/api/notice-api.ts
  data/wallet/merchantGuideContents.ts
  lib/parseJwt.ts
  middleware.ts
  public/search-icon.png
  public/simple-bar-chart.png
  public/simple-monthly-calendar.png
Labels: FEAT

#64 Feat: 가맹점주 토큰 -> 예금 전환 페이지 구현
  app/merchant/dashboard/components/VoucherSearch.tsx
  app/merchant/wallet/components/ConvertButton.tsx
  app/merchant/wallet/convert/api/token-to-deposit.ts
  app/merchant/wallet/convert/api/verify-merchant-simple-password.ts
  app/merchant/wallet/convert/components/AmountStep.tsx
  app/merchant/wallet/convert/components/BalanceCard.tsx
  app/merchant/wallet/convert/components/CompleteStep.tsx
  app/merchant/wallet/convert/components/ConfirmStep.tsx
  app/merchant/wallet/convert/components/ConvertPreview.tsx
  app/merchant/wallet/convert/components/ProcessingStep.tsx
  app/merchant/wallet/convert/components/VerifySimplePassword.tsx
  app/merchant/wallet/convert/page.tsx
Labels: FEAT

#65 feat: 가맹점주 공지사항 페이지 구현 및 api 연동
  app/merchant/notice/[id]/page.tsx
  app/merchant/notice/api/notice-api.ts
  app/merchant/notice/components/NoticeItem.tsx
  app/merchant/notice/components/NoticeList.tsx
  app/merchant/notice/components/SkeletonDetail.tsx
  app/merchant/notice/components/SkeletonList.tsx
  app/merchant/notice/page.tsx
Labels: FEAT

#66 feat: 간편 비밀번호 확인 버튼 비활성화 기능 추가
  app/dashboard/api/fetch-recent-transactions.ts
  app/dashboard/page.tsx
  app/merchant/dashboard/api/merchant-recent-transactions.ts
  app/merchant/dashboard/components/TransactionList.tsx
  app/merchant/wallet/totaltransaction/[id]/page.tsx
  app/merchant/wallet/totaltransaction/page.tsx
  app/payment/api/payment.ts
  app/payment/components/VerifySimplePassword.tsx
  app/payment/page.tsx
  app/wallet/api/fetch-transactions-detail.ts
  app/wallet/api/fetch-transactions.ts
  app/wallet/components/common/TransactionCardContent.tsx
  app/wallet/totaltransaction/[id]/page.tsx
  components/common/TransactionCardContent.tsx
  components/common/TransactionList.tsx
  components/virtual-keypad.tsx
Labels: REFACTOR, FEAT

#67 refactor: 결제내역 조회 관련 수정
  app/wallet/components/common/TransactionList.tsx
Labels: REFACTOR

#68 Feat: 가맹점주 마이페이지 구현
  app/merchant/dashboard/api/merchant-recent-transactions.ts
  app/merchant/dashboard/components/SalesStatistics.tsx
  app/merchant/dashboard/components/WalletCard.tsx
  app/merchant/mypage/api/merchant-info.ts
  app/merchant/mypage/api/merchant-logout.ts
  app/merchant/mypage/change-password/api/password-update.ts
  app/merchant/mypage/change-password/components/ChangePasswordCardHeader.tsx
  app/merchant/mypage/change-password/components/ChangePasswordForm.tsx
  app/merchant/mypage/change-password/components/ChangePasswordHeader.tsx
  app/merchant/mypage/change-password/components/ChangePasswordSuccess.tsx
  app/merchant/mypage/change-password/components/PasswordInput.tsx
  app/merchant/mypage/change-password/page.tsx
  app/merchant/mypage/change-simple-password/api/change-simple-password.ts
  app/merchant/mypage/change-simple-password/components/ChangePinHeader.tsx
  app/merchant/mypage/change-simple-password/components/ChangePinLayout.tsx
  app/merchant/mypage/change-simple-password/components/StepComplete.tsx
  app/merchant/mypage/change-simple-password/components/StepConfirmPin.tsx
  app/merchant/mypage/change-simple-password/components/StepIntro.tsx
  app/merchant/mypage/change-simple-password/components/StepNewPin.tsx
  app/merchant/mypage/change-simple-password/components/StepVerifyCurrent.tsx
  app/merchant/mypage/change-simple-password/page.tsx
  app/merchant/mypage/components/LogoutButton.tsx
  app/merchant/mypage/components/MenuList.tsx
  app/merchant/mypage/components/MerchantMypageHeader.tsx
  app/merchant/mypage/components/ProfileCard.tsx
  app/merchant/mypage/data/menu-items.ts
  app/merchant/mypage/info/components/MerchantInfoCard.tsx
  app/merchant/mypage/info/components/MerchantInfoHeader.tsx
  app/merchant/mypage/info/page.tsx
  app/merchant/mypage/page.tsx
  app/merchant/mypage/reset-simple-password/api/reset-simple-password.ts
  app/merchant/mypage/reset-simple-password/components/ResetPinComplete.tsx
  app/merchant/mypage/reset-simple-password/components/ResetPinForm.tsx
  app/merchant/mypage/reset-simple-password/components/ResetPinHeader.tsx
  app/merchant/mypage/reset-simple-password/page.tsx
  app/merchant/notice/page.tsx
  app/merchant/reset-password/api/reset-password-auth.ts
  app/merchant/reset-password/components/ResetPasswordComplete.tsx
  app/merchant/reset-password/components/ResetPasswordForm.tsx
  app/merchant/reset-password/page.tsx
  app/merchant/wallet/components/WalletCard.tsx
  app/mypage/edit/components/card/EmailChangeDialog.tsx
  app/mypage/edit/components/card/ProfileCardHeader.tsx
  components/common/TransactionCardContent.tsx
  components/page-header.tsx
  middleware.ts
Labels: FEAT

#69 feat: 유저 비밀번호 변경 페이지 구현
  app/mypage/change-password/api/password-update.ts
  app/mypage/change-password/components/ChangePasswordCardHeader.tsx
  app/mypage/change-password/components/ChangePasswordForm.tsx
  app/mypage/change-password/components/ChangePasswordHeader.tsx
  app/mypage/change-password/components/ChangePasswordSuccess.tsx
  app/mypage/change-password/components/PasswordInput.tsx
  app/mypage/change-password/page.tsx
  app/mypage/page.tsx
Labels: FEAT

#72 refactor: UI 수정
  app/merchant/dashboard/page.tsx
  app/merchant/mypage/change-simple-password/components/ChangePinHeader.tsx
Labels: REFACTOR

#76 refactor: 간편비밀번호 검증 요청 api 제거
  app/merchant/wallet/convert/components/VerifySimplePassword.tsx
  app/merchant/wallet/convert/page.tsx
Labels: REFACTOR

#77 feat: 마이페이지 메뉴에 qrcode 추가
  app/merchant/mypage/data/menu-items.ts
  app/merchant/mypage/qr-code/data/payment.ts
  app/merchant/mypage/qr-code/data/storeqr.ts
  app/merchant/mypage/qr-code/page.tsx
  app/payment/components/AmountBox.tsx
  app/payment/components/PaymentCarousel.tsx
  app/payment/components/ResultBox.tsx
  app/payment/page.tsx
  data/dashboard/recommendedVouchers.ts
Labels: FEAT

#78 refactor: user page ui 수정
  app/dashboard/page.tsx
  app/merchant/wallet/convert/components/AmountStep.tsx
  app/wallet/components/AmountStep.tsx
  app/wallet/components/common/TransactionCardContent.tsx
  app/wallet/components/common/TransactionList.tsx
  app/wallet/page.tsx
  app/wallet/totaltransaction/[id]/page.tsx
  app/wallet/totaltransaction/page.tsx
  components/common/AmountInput.tsx
Labels: REFACTOR

#79 feat: QRCode 화면 구현
  app/merchant/mypage/qr-code/components/MerchantInfoCard.tsx
  app/merchant/mypage/qr-code/components/PaymentGuideSection.tsx
  app/merchant/mypage/qr-code/components/QRCodeSection.tsx
  app/merchant/mypage/qr-code/components/QrHeader.tsx
  app/merchant/mypage/qr-code/data/storeqr.ts
  app/merchant/mypage/qr-code/page.tsx
  package-lock.json
  package.json
Labels: FEAT

#91 feat: 알림 페이지 구현
  app/notifications/api/delete-notifications.ts
  app/notifications/api/fetch-notifications-category.ts
  app/notifications/api/fetch-notifications.ts
  app/notifications/components/NotificationIcon.tsx
  app/notifications/components/NotificationItem.tsx
  app/notifications/components/NotificationList.tsx
  app/notifications/components/NotificationTabs.tsx
  app/notifications/page.tsx
  app/notifications/settings/api/fetch-notification-setting.ts
  app/notifications/settings/api/update-notification-setting.ts
  app/notifications/settings/components/NotificationPolicyInfo.tsx
  app/notifications/settings/page.tsx
Labels: FEAT

#94 refactor: PaymentCarousel ui 수정
  app/payment/components/PaymentCarousel.tsx
  app/payment/page.tsx
Labels: REFACTOR

#95 feat: 알림 기능 연동
  app/dashboard/page.tsx
  app/notifications/page.tsx
  components/common/NotificationToast.tsx
  package-lock.json
  package.json
Labels: FEAT

#98 refactor: 유저 정보 수정 페이지 리팩토링
  app/mypage/edit/api/email.ts
  app/mypage/edit/api/update-user-info.ts
  app/mypage/edit/components/card/EmailChangeDialog.tsx
  app/mypage/edit/components/card/ProfileForm.tsx
  app/mypage/edit/page.tsx
Labels: REFACTOR

#104 :sparkles: Feat: CICD 파일 추가
  .github/workflows/deploy.yml
  Dockerfile
Labels: FEAT

#108 refactor: txHash 예외처리
  app/wallet/totaltransaction/[id]/page.tsx
Labels: REFACTOR

#110 Refactor: 가맹점주 회원가입 business 부분 수정
  app/merchant/signup/business/components/AddressSearchModal.tsx
  app/merchant/signup/business/components/InfoStep.tsx
Labels: REFACTOR

#113 fix: Hikaripool error 해결
  app/dashboard/page.tsx
Labels: FIX

#115 refactor: merchant qrcode 수정
  app/merchant/mypage/qr-code/data/storeqr.ts
Labels: REFACTOR

#117 Feat/#114 kakao map 상세 페이지 구현 및 클러스터링 적용 완료
  app/offline-stores/[id]/page.tsx
  app/offline-stores/api/store-api.ts
  app/offline-stores/components/LoadingSpinner.tsx
  app/offline-stores/components/StoreQrBunny.tsx
  app/offline-stores/page.tsx
  app/offline-stores/utils/map-utils.ts
Labels: FEAT

#118 Refactor: Skeleton 적용 및 UI 수정
  app/dashboard/loading/NoticeSkeleton.tsx
  app/dashboard/loading/TransactionListSkeleton.tsx
  app/dashboard/loading/WalletCardSkeleton.tsx
  app/dashboard/page.tsx
  app/landing-page/components/CBDCTab.tsx
  app/landing-page/components/PullHandle.tsx
  app/mypage/change-pin/components/StepIntro.tsx
  app/mypage/change-pin/components/StepVerifyCurrent.tsx
  app/mypage/change-pin/page.tsx
  app/mypage/components/MypageSkeleton.tsx
  app/mypage/page.tsx
  app/payment/components/VerifySimplePassword.tsx
  app/payment/page.tsx
  app/wallet/components/AmountStep.tsx
  app/wallet/components/convertSkeleton.tsx
  app/wallet/convert/[type]/page.tsx
  app/wallet/page.tsx
  components/common/Header.tsx
  components/common/NotificationToast.tsx
  lib/fetchWithAuth.ts
Labels: REFACTOR

#120 :bug: fix: KaKao Type Error 해결
  app/merchant/signup/business/components/AddressSearchModal.tsx
  app/merchant/signup/business/components/InfoStep.tsx
  app/merchant/signup/business/page.tsx
  app/offline-stores/page.tsx
  app/offline-stores/utils/map-overlay.ts
  app/offline-stores/utils/map-utils.ts
  app/payment/page.tsx
  components/qr-code.tsx
  components/ui/chart.tsx
Labels: FEAT

#124 [DEPLOY] v1.0.3
  app/vouchers/components/VoucherCard.tsx
  next.config.ts
Labels: RELEASE

#128 feat: 가맹점주 알림 페이지 구현 및 api 연동
  app/merchant/dashboard/page.tsx
  app/merchant/notifications/api/delete-merchant-notifications.ts
  app/merchant/notifications/api/fetch-merchant-notifications-category.ts
  app/merchant/notifications/api/fetch-merchant-notifications.ts
  app/merchant/notifications/components/NotificationEmptyState.tsx
  app/merchant/notifications/components/NotificationHeader.tsx
  app/merchant/notifications/components/NotificationIcon.tsx
  app/merchant/notifications/components/NotificationItem.tsx
  app/merchant/notifications/components/NotificationList.tsx
  app/merchant/notifications/components/NotificationSkeleton.tsx
  app/merchant/notifications/components/NotificationTabs.tsx
  app/merchant/notifications/page.tsx
  app/merchant/notifications/settings/api/fetch-merchant-notification-setting.ts
  app/merchant/notifications/settings/api/update-merchant-notification-setting.ts
  app/merchant/notifications/settings/components/NotificationPolicyInfo.tsx
  app/merchant/notifications/settings/components/NotificationSettingHeader.tsx
  app/merchant/notifications/settings/components/NotificationSettingItem.tsx
  app/merchant/notifications/settings/components/NotificationSettingSkeleton.tsx
  app/merchant/notifications/settings/page.tsx
  app/merchant/wallet/convert/components/CompleteStep.tsx
  app/merchant/wallet/convert/page.tsx
Labels: FEAT
